"""Binance USDT-M Futures order placement (G6.4 — CEX hedge leg).

The actual order-placement surface for the CEX hedge leg of the
funding-arb. Sits on top of:
  - G6.1 `binance_exchange_info.py` — symbol filter cache; we MUST snap-
    round quantity through `quantity_from_notional` + `round_qty_down` and
    final-gate it with `passes_min_notional` BEFORE submission, or every
    order will reject `-4164` (MIN_NOTIONAL) or `-1111` (PRECISION).
  - G6.2 `binance_auth.py` — `signed_post` / `signed_get` / (new in G6.4)
    `signed_delete` for the HMAC plumbing.
  - G6.2 `binance_startup_check.py` — `assert_one_way_position_mode`
    refuses to run in hedge mode (audit H3). G6.4 invokes this as the
    last gate before broadcasting a real order; failing means the
    operator hasn't flipped the account back to one-way via the UI.
  - G5.2 `settings.live_binance_enabled` — global kill-switch. Defaults
    False. Mirrors the gate-stack pattern from `gmx_signer.submit_signed`.

WHY THIS EXISTS — short version:
  G6.1-G6.3 shipped the READ surface (filters + auth + smoke). G6.4 is
  the WRITE surface. This is where a real order can leave the box and
  reach Binance. Every safety belt above is here.

GATE STACK (`place_market_order`):

    | dry_run | live_binance_enabled | position-mode | Broadcast? |
    |---------|----------------------|---------------|------------|
    | True    | any                  | any           | NO (sim)   |
    | False   | False                | any           | NO (gate)  |
    | False   | True                 | HEDGE / unkn  | NO (gate)  |
    | False   | True                 | one-way       | YES        |

  NO real broadcast unless ALL THREE are simultaneously true:
    dry_run=False AND live_binance_enabled=True AND position-mode is one-way.
  Mirrors the GMX side's `submit_signed` gate matrix exactly so an
  operator who knows one knows the other.

WHAT THIS IS NOT (deferred to G7.x):
  - NO consumption of `funding_arb:signals`. The runtime wiring is G7.1.
  - NO position reconciliation loop. That's G7.x — for now G6.4 ships
    the per-call helpers and the consumer composes them.
  - NO TWAP / spread / limit-orders. MARKET-only this PR; LIMIT is a
    later iteration once the basic surface is proven.
  - NO retry logic on partial fills or post-broadcast timeouts. The
    audit §12 reconciliation pattern (query-via-clientOrderId) is
    implemented as a discoverable helper (`get_order_status`) but the
    caller decides retry semantics.

SYMBOL / SIDE / TYPE WHITELIST:
  Per the audit §H1, only the 5 funding-arb basket symbols are allowed.
  Sides: BUY (open long / close short) and SELL (open short / close
  long). Types: MARKET only — LIMIT-IOC was scoped out for G6.4 because
  the funding-arb hedge leg is always taker (matches GMX's market-fill
  on the other side).

IDEMPOTENCY (newClientOrderId):
  Every order generated by `place_market_order` carries a
  `newClientOrderId` of the form:
      <settings.binance_order_idempotency_prefix><uuid4_hex[:16]>
  (default `gmx-strategies-` + 16 hex = 31 chars; fits Binance's 36-cap
  regex `^[\\.A-Z\\:/a-z0-9_-]{1,36}$`).

  Callers can pre-generate and pass `client_order_id` for deterministic
  retry — re-issuing the SAME id is the audit §12 reconciliation pattern:
  if the order already exists, Binance returns the existing state;
  otherwise the new order is placed. Either way the caller gets a
  canonical state from a single round-trip on retry.

SECRETS HYGIENE:
  NEVER log the api_key/secret/signed query. Same rules as binance_auth.
  We log: symbol, side, type, quantity, status, error_code, error_msg.

  We log REQUEST params (the dict that would be signed) on dry_run
  because that's the operator's only visibility into what would be sent
  — and the dict does NOT contain the signature or api_key. The signed
  payload (signature, X-MBX-APIKEY) is built downstream in
  `binance_auth._signed_request` and never crosses back into this
  module.

ERROR CODE MAPPING:
  Audit §12 catalogs the codes we care about. We map each known code to
  a stable human-readable message string on `OrderResult.error_msg`:

    -1013 INVALID_MESSAGE         "invalid_message_or_lot_size"
    -1111 BAD_PRECISION           "precision_mismatch"
    -2010 NEW_ORDER_REJECTED      "new_order_rejected"
    -2019 MARGIN_NOT_SUFFICIENT   "margin_not_sufficient"
    -4061 POSITION_SIDE_NOT_MATCH "position_side_not_match_hedge_mode"
    -4164 MIN_NOTIONAL            "below_min_notional_exchange"

  Unknown codes are surfaced verbatim (`OrderResult.error_code` carries
  the raw int; `error_msg` carries the raw Binance message string).
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from typing import Any

import httpx

from gmx_strategies import binance_exchange_info, binance_startup_check
from gmx_strategies.binance_auth import signed_delete, signed_get, signed_post
from gmx_strategies.settings import settings

log = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────────
# Whitelists — symbols / sides / types we ship in G6.4
# ──────────────────────────────────────────────────────────────────────────

# The 5 funding-arb basket symbols. Refusing anything outside this set —
# even if `exchangeInfo` has it — is the audit's H1 / Whitelist guidance:
# "Drop strange symbols at the boundary, don't trust filter-presence as
# a proxy for whitelisting."
ALLOWED_SYMBOLS = frozenset({
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "DOGEUSDT", "XRPUSDT",
})

# BUY opens longs (or closes shorts); SELL opens shorts (or closes longs).
ALLOWED_SIDES = frozenset({"BUY", "SELL"})

# G6.4 ships MARKET only — LIMIT (IOC / GTC) is scoped out for v0.1.
ALLOWED_TYPES = frozenset({"MARKET"})


# ──────────────────────────────────────────────────────────────────────────
# Error-code → stable string mapping (audit §12)
# ──────────────────────────────────────────────────────────────────────────

# Maps Binance numeric codes to short stable identifiers. The MESSAGE
# returned by Binance is also surfaced (raw) on `error_msg`; this map is
# the structural classifier callers can match on without parsing strings.
_ERROR_CODE_TO_SLUG: dict[int, str] = {
    -1013: "invalid_message_or_lot_size",
    -1111: "precision_mismatch",
    -2010: "new_order_rejected",
    -2019: "margin_not_sufficient",
    -4061: "position_side_not_match_hedge_mode",
    -4164: "below_min_notional_exchange",
}


def _classify_error(code: int | None) -> str | None:
    """Map a Binance error code to a stable slug, or None if unknown.

    Used for logging + result tagging. Callers can also branch on the
    raw `error_code` int — the slug is for human-readable summaries.
    """
    if code is None:
        return None
    return _ERROR_CODE_TO_SLUG.get(code)


# ──────────────────────────────────────────────────────────────────────────
# Frozen dataclasses — the public types
# ──────────────────────────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class OrderRequest:
    """Validated order request — ready to be turned into signed params.

    Construction is via the public `place_market_order` helper; the
    dataclass itself does NOT validate (since by the time we build one,
    pre-flight has already run). It's a transport.

    Fields:
      symbol            — one of ALLOWED_SYMBOLS
      side              — BUY | SELL
      type              — MARKET (only MARKET ships in G6.4)
      quantity          — base-asset units, ALREADY rounded to lot_step
      reduce_only       — when True sends `reduceOnly=true`. Audit §2: in
                          one-way mode, reduceOnly=true caps the close at
                          the existing position size — useful safety on
                          every close. NOT permitted in hedge mode (we
                          gate against hedge mode at the executor boot).
      client_order_id   — Binance `newClientOrderId`. Auto-generated if
                          not supplied. Always set in the request.
    """

    symbol: str
    side: str
    type: str
    quantity: float
    reduce_only: bool = False
    client_order_id: str | None = None

    def to_signed_params(self) -> dict[str, str | int | float]:
        """Build the param dict for `signed_post(/fapi/v1/order, ...)`.

        Binance accepts query-string-only POST; our `signed_post` puts the
        full param dict on the URL. We always set:

          - `newOrderRespType=RESULT` — synchronous response with the
            final FILLED state for MARKET. Audit §2 recommended this so
            we get `executedQty` / `cumQuote` / `avgPrice` in one round-
            trip without a separate query.

          - `recvWindow` is added downstream by `_build_signed_query`;
            do NOT add it here.

        `quantity` is sent as a number (float) — Binance accepts either
        scientific or fixed, but we already snap-rounded the value to
        `lot_step` via Decimal math in `binance_exchange_info`, so the
        float-stringification is safe within the per-symbol precision.

        `reduceOnly` is sent as the literal string `"true"` / `"false"`
        because Binance's docs explicitly say the field is STRING
        (case-insensitive). Sending a Python bool would urlencode to
        "True" / "False" — Binance's parser accepts lowercase only.

        `newClientOrderId` is REQUIRED for our idempotency pattern; the
        constructor pre-fills it if the caller didn't.
        """
        params: dict[str, str | int | float] = {
            "symbol": self.symbol,
            "side": self.side,
            "type": self.type,
            "quantity": self.quantity,
            "newOrderRespType": "RESULT",
        }
        # Binance wants the boolean as a lowercase string per docs.
        if self.reduce_only:
            params["reduceOnly"] = "true"
        if self.client_order_id is not None:
            params["newClientOrderId"] = self.client_order_id
        return params


@dataclass(frozen=True, slots=True)
class OrderResult:
    """Outcome of `place_market_order` — sim, gate-fail, or live result.

    The shape is shared across all three branches so callers can pattern-
    match on `submitted` + `gate_blocked` + `error_code` without a sum
    type.

    - `submitted=True`  → broadcast went out, Binance returned 200 with
                          the FILLED state. `order_id` + `status` +
                          `executed_qty` + `avg_price` + `cum_quote`
                          populated.

    - `submitted=False, gate_blocked=<reason>` → pre-flight or gate
                          refused. `dry_run_request` carries the exact
                          dict that WOULD have been signed. Useful for
                          dry-run debugging.

    - `submitted=False, error_code=<int>` → broadcast went out, Binance
                          returned an error (non-200 or 200 with `code`
                          field). `error_code` + `error_msg` populated.

    - `submitted=False` with NO `gate_blocked` and NO `error_code` →
                          pre-flight check itself failed locally (bad
                          side, unknown symbol, below-min-notional).
                          `error_code=-1` is the convention to mark a
                          local rejection (different from any real
                          Binance code which are all in 4-digit range).
                          `error_msg` describes the local reason.
    """

    submitted: bool
    dry_run_request: dict[str, str | int | float] | None
    order_id: int | None
    client_order_id: str | None
    status: str | None
    executed_qty: float | None
    avg_price: float | None
    cum_quote: float | None
    error_code: int | None
    error_msg: str | None
    gate_blocked: str | None
    # `error_slug` is the stable classifier from `_ERROR_CODE_TO_SLUG`
    # when `error_code` matches a known audit-§12 code; None otherwise.
    # Callers prefer matching on this over the raw int — the slug is the
    # contract; the int is the transport.
    error_slug: str | None = field(default=None)


# ──────────────────────────────────────────────────────────────────────────
# Helpers — pre-flight + client-id generation
# ──────────────────────────────────────────────────────────────────────────


def _generate_client_order_id() -> str:
    """Build a `newClientOrderId` matching Binance's regex.

    Format: `<settings.binance_order_idempotency_prefix><uuid4_hex[:16]>`.
    Default prefix `gmx-strategies-` + 16 hex chars = 31 chars total
    (Binance cap is 36). The hex is a 64-bit slice of a uuid4 — collisions
    are not a practical concern at our 10-orders-per-day cadence.

    The regex Binance enforces is `^[\\.A-Z\\:/a-z0-9_-]{1,36}$`. The
    default prefix uses only `[a-z0-9-]` so we stay well within bounds.
    Operators overriding `binance_order_idempotency_prefix` MUST keep the
    prefix to the allowed character class.
    """
    return f"{settings.binance_order_idempotency_prefix}{uuid.uuid4().hex[:16]}"


def _make_local_error(
    *,
    error_msg: str,
    error_code: int = -1,
    client_order_id: str | None = None,
    dry_run_request: dict[str, str | int | float] | None = None,
) -> OrderResult:
    """Build an OrderResult that represents a local pre-flight rejection.

    Local errors use `error_code=-1` as a sentinel (different from any
    real Binance code, all of which are 4-digit negatives). `error_slug`
    is left None — slugs are reserved for known Binance codes.
    """
    return OrderResult(
        submitted=False,
        dry_run_request=dry_run_request,
        order_id=None,
        client_order_id=client_order_id,
        status=None,
        executed_qty=None,
        avg_price=None,
        cum_quote=None,
        error_code=error_code,
        error_msg=error_msg,
        gate_blocked=None,
        error_slug=None,
    )


def _parse_binance_response(
    body: dict[str, Any],
    *,
    client_order_id: str | None,
) -> OrderResult:
    """Parse a Binance order response into an OrderResult.

    Binance returns one of two shapes for /fapi/v1/order POST:

      Happy (newOrderRespType=RESULT):
        {
          "orderId": 12345,
          "clientOrderId": "gmx-strategies-...",
          "symbol": "SOLUSDT",
          "status": "FILLED",
          "executedQty": "0.034",
          "cumQuote": "5.12",
          "avgPrice": "150.58",
          "side": "BUY",
          "type": "MARKET",
          ... // other fields we ignore
        }

      Error (e.g. -4164, -1111, -2019, -2010, -4061):
        {
          "code": -4164,
          "msg": "Order's notional must be no smaller than 5.0."
        }

    `code` being present (and an int) is the error sentinel — even if
    `status` were also somehow present, the canonical error shape uses
    `{code, msg}` per the audit + Binance error-code docs.

    On a happy response missing some optional numeric field (e.g. older
    Binance behavior where ACK was returned by accident), we surface
    what we got and leave the missing fields as None — caller can still
    use `submitted=True` + `order_id` to reconcile via `get_order_status`.
    """
    code = body.get("code")
    msg = body.get("msg")
    if isinstance(code, int):
        # Error path
        err_msg = msg if isinstance(msg, str) else "unknown_error"
        return OrderResult(
            submitted=False,
            dry_run_request=None,
            order_id=None,
            client_order_id=client_order_id,
            status=None,
            executed_qty=None,
            avg_price=None,
            cum_quote=None,
            error_code=code,
            error_msg=err_msg,
            gate_blocked=None,
            error_slug=_classify_error(code),
        )

    # Happy path — best-effort numeric coercion (Binance returns strings)
    order_id_raw = body.get("orderId")
    order_id = order_id_raw if isinstance(order_id_raw, int) else None
    status_raw = body.get("status")
    status = status_raw if isinstance(status_raw, str) else None
    actual_client_order_id = body.get("clientOrderId")
    if isinstance(actual_client_order_id, str) and actual_client_order_id:
        client_order_id = actual_client_order_id

    def _to_float(raw: Any) -> float | None:
        if not isinstance(raw, (str, int, float)):
            return None
        try:
            value = float(raw)
        except (ValueError, TypeError):
            return None
        # NaN / inf guard
        if value != value or value in (float("inf"), float("-inf")):
            return None
        return value

    return OrderResult(
        submitted=True,
        dry_run_request=None,
        order_id=order_id,
        client_order_id=client_order_id,
        status=status,
        executed_qty=_to_float(body.get("executedQty")),
        avg_price=_to_float(body.get("avgPrice")),
        cum_quote=_to_float(body.get("cumQuote")),
        error_code=None,
        error_msg=None,
        gate_blocked=None,
        error_slug=None,
    )


# ──────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────


async def place_market_order(
    symbol: str,
    side: str,
    notional_usd: float,
    *,
    mark_price: float,
    reduce_only: bool = False,
    client_order_id: str | None = None,
    dry_run: bool = True,
    client: httpx.AsyncClient | None = None,
) -> OrderResult:
    """Place (or dry-run) a MARKET order on Binance USDT-M Futures.

    Pre-flight (all checked before ANY HTTP call):
      1. side ∈ ALLOWED_SIDES
      2. symbol ∈ ALLOWED_SYMBOLS
      3. Symbol present in cached exchangeInfo (`get_cached_exchange_info`)
      4. Compute quantity via `quantity_from_notional(info, notional_usd,
         mark_price)`. Zero → below-lot-min rejection.
      5. `passes_min_notional(info, qty, mark_price)` → False = exchange
         min-notional rejection (e.g. BTC at $5 cap when min is $50).
      6. Generate `client_order_id` if not supplied (audit §12 idempotency).

    On `dry_run=True` (the default):
      Returns `OrderResult(submitted=False, dry_run_request=<params>)`.
      The dict is what WOULD have been signed and POSTed — operators
      can inspect it without anything reaching Binance.

    On `dry_run=False`:
      GATE 1: `settings.live_binance_enabled` MUST be True.
              False → `gate_blocked="live_binance_enabled=False"`,
              no broadcast.
      GATE 2: `assert_one_way_position_mode()` MUST succeed.
              Hedge or unknown → `gate_blocked="hedge_mode_or_api_down"`,
              no broadcast.
      Then issues `signed_post("/fapi/v1/order", ...)`. The response is
      parsed into `OrderResult` — `submitted=True` on the happy path,
      `error_code`/`error_msg` populated on a Binance reject.

    Args:
        symbol: Must be one of ALLOWED_SYMBOLS (whitelist enforced).
        side: Must be one of ALLOWED_SIDES.
        notional_usd: Target USD notional. Snap-rounded to lot_step via
            `quantity_from_notional`.
        mark_price: Current mark price for the symbol (caller's choice
            of price source — typically `binance_funding` markPrice or
            chainlink-streams benchmark). Used for sizing + min_notional
            check ONLY; the actual fill price is whatever Binance returns.
        reduce_only: When True, set `reduceOnly=true`. Use on CLOSE orders.
        client_order_id: Optional pre-supplied id (caller-controlled
            retry). When None, one is generated.
        dry_run: When True (default), do not broadcast. Even with
            dry_run=False, the gate-stack must clear.
        client: Optional shared httpx.AsyncClient.

    Returns:
        OrderResult — never raises.
    """
    # ── Pre-flight 1: side whitelist ─────────────────────────────────
    if side not in ALLOWED_SIDES:
        log.warning("binance_order.bad_side side=%s", side)
        return _make_local_error(
            error_msg=f"side not allowed: {side!r} (allowed: {sorted(ALLOWED_SIDES)})",
            client_order_id=client_order_id,
        )

    # ── Pre-flight 2: symbol whitelist ──────────────────────────────
    if symbol not in ALLOWED_SYMBOLS:
        log.warning("binance_order.bad_symbol symbol=%s", symbol)
        return _make_local_error(
            error_msg=(
                f"symbol not in whitelist: {symbol!r} "
                f"(allowed: {sorted(ALLOWED_SYMBOLS)})"
            ),
            client_order_id=client_order_id,
        )

    # ── Pre-flight 3: exchangeInfo for symbol ───────────────────────
    info_map = await binance_exchange_info.get_cached_exchange_info(client=client)
    info = info_map.get(symbol)
    if info is None:
        log.warning(
            "binance_order.symbol_missing_in_exchange_info symbol=%s "
            "n_known=%d", symbol, len(info_map),
        )
        return _make_local_error(
            error_msg=f"symbol not in exchange_info: {symbol!r}",
            client_order_id=client_order_id,
        )

    # ── Pre-flight 4: compute quantity from notional ────────────────
    qty = binance_exchange_info.quantity_from_notional(
        info, notional_usd, mark_price,
    )
    if qty <= 0:
        log.warning(
            "binance_order.qty_below_lot_min symbol=%s notional_usd=%.4f "
            "mark_price=%.4f lot_step=%s lot_min=%s",
            symbol, notional_usd, mark_price, info.lot_step, info.lot_min,
        )
        return _make_local_error(
            error_msg=(
                f"below_lot_min symbol={symbol} notional_usd={notional_usd} "
                f"mark_price={mark_price} lot_step={info.lot_step} "
                f"lot_min={info.lot_min}"
            ),
            client_order_id=client_order_id,
        )

    # ── Pre-flight 5: min_notional (after rounding!) ────────────────
    if not binance_exchange_info.passes_min_notional(info, qty, mark_price):
        log.warning(
            "binance_order.below_min_notional symbol=%s qty=%s "
            "mark_price=%.4f min_notional=%s",
            symbol, qty, mark_price, info.min_notional,
        )
        return _make_local_error(
            error_msg=(
                f"below_min_notional symbol={symbol} qty={qty} "
                f"mark_price={mark_price} min_notional={info.min_notional}"
            ),
            client_order_id=client_order_id,
        )

    # ── Pre-flight 6: generate client_order_id if absent ────────────
    if client_order_id is None:
        client_order_id = _generate_client_order_id()

    # ── Assemble the request ────────────────────────────────────────
    req = OrderRequest(
        symbol=symbol,
        side=side,
        type="MARKET",
        quantity=qty,
        reduce_only=reduce_only,
        client_order_id=client_order_id,
    )
    params = req.to_signed_params()

    # ── Dry-run path: do NOT call Binance ───────────────────────────
    if dry_run:
        log.info(
            "binance_order.dry_run symbol=%s side=%s qty=%s "
            "client_order_id=%s reduce_only=%s",
            symbol, side, qty, client_order_id, reduce_only,
        )
        return OrderResult(
            submitted=False,
            dry_run_request=params,
            order_id=None,
            client_order_id=client_order_id,
            status=None,
            executed_qty=None,
            avg_price=None,
            cum_quote=None,
            error_code=None,
            error_msg=None,
            gate_blocked=None,
            error_slug=None,
        )

    # ── Live path: GATE 1 — global kill switch ──────────────────────
    if not settings.live_binance_enabled:
        log.warning(
            "binance_order.gate live=disabled symbol=%s side=%s qty=%s "
            "(settings.live_binance_enabled=False)",
            symbol, side, qty,
        )
        return OrderResult(
            submitted=False,
            dry_run_request=params,
            order_id=None,
            client_order_id=client_order_id,
            status=None,
            executed_qty=None,
            avg_price=None,
            cum_quote=None,
            error_code=None,
            error_msg=None,
            gate_blocked="live_binance_enabled=False",
            error_slug=None,
        )

    # ── Live path: GATE 2 — position-mode (audit H3) ────────────────
    try:
        await binance_startup_check.assert_one_way_position_mode()
    except RuntimeError as exc:
        log.warning(
            "binance_order.gate position_mode=blocked symbol=%s err=%s",
            symbol, exc,
        )
        return OrderResult(
            submitted=False,
            dry_run_request=params,
            order_id=None,
            client_order_id=client_order_id,
            status=None,
            executed_qty=None,
            avg_price=None,
            cum_quote=None,
            error_code=None,
            error_msg=str(exc),
            gate_blocked="hedge_mode_or_api_down",
            error_slug=None,
        )

    # ── Live path: broadcast ────────────────────────────────────────
    log.info(
        "binance_order.broadcast symbol=%s side=%s qty=%s "
        "client_order_id=%s reduce_only=%s",
        symbol, side, qty, client_order_id, reduce_only,
    )
    body = await signed_post("/fapi/v1/order", params, client=client)
    if not isinstance(body, dict):
        # `signed_post` returned None (HTTP error) or a list (impossible
        # for /fapi/v1/order but defensive). Surface as a transport
        # failure — we don't know order state. Caller can reconcile via
        # `get_order_status(client_order_id=...)`.
        log.error(
            "binance_order.broadcast_no_body symbol=%s client_order_id=%s",
            symbol, client_order_id,
        )
        return OrderResult(
            submitted=False,
            dry_run_request=params,
            order_id=None,
            client_order_id=client_order_id,
            status=None,
            executed_qty=None,
            avg_price=None,
            cum_quote=None,
            error_code=None,
            error_msg="no_response_body_from_signed_post",
            gate_blocked=None,
            error_slug=None,
        )

    result = _parse_binance_response(body, client_order_id=client_order_id)
    if result.submitted:
        log.info(
            "binance_order.broadcast_ok symbol=%s order_id=%s status=%s "
            "executed_qty=%s avg_price=%s cum_quote=%s",
            symbol, result.order_id, result.status, result.executed_qty,
            result.avg_price, result.cum_quote,
        )
    else:
        log.warning(
            "binance_order.broadcast_reject symbol=%s code=%s slug=%s msg=%s",
            symbol, result.error_code, result.error_slug, result.error_msg,
        )
    return result


async def get_order_status(
    symbol: str,
    *,
    order_id: int | None = None,
    client_order_id: str | None = None,
    client: httpx.AsyncClient | None = None,
) -> OrderResult | None:
    """Reconcile an order's state via `GET /fapi/v1/order`.

    Per audit §12: on any network-ambiguous failure (request sent,
    response truncated, timeout), call this with the SAME `client_order_id`
    we generated for the submit. If the order exists, Binance returns
    its canonical state. If it does not, Binance returns `-2013 Order
    does not exist.` — the caller can safely retry with the same id.

    Args:
        symbol: Must be one of ALLOWED_SYMBOLS (whitelist enforced even
            for reads, to prevent typo-driven queries of unrelated
            symbols).
        order_id: Binance's numeric orderId (from a previous OrderResult).
        client_order_id: Caller-supplied idempotency id. Either this OR
            order_id must be set; if both are set Binance uses orderId
            and ignores origClientOrderId.
        client: Optional shared httpx.AsyncClient.

    Returns:
        OrderResult with the current state (`submitted=True` if the
        order exists in any state — including CANCELED / EXPIRED, the
        existence is the contract), or an OrderResult with `error_code`
        / `error_msg` on a Binance error. Returns None ONLY if the
        symbol is outside the whitelist (caller bug).
    """
    if symbol not in ALLOWED_SYMBOLS:
        log.warning("binance_order.get_order_status.bad_symbol symbol=%s", symbol)
        return None
    if order_id is None and not client_order_id:
        log.warning(
            "binance_order.get_order_status.no_id symbol=%s — "
            "must supply order_id or client_order_id", symbol,
        )
        return None

    params: dict[str, str | int | float] = {"symbol": symbol}
    if order_id is not None:
        params["orderId"] = order_id
    elif client_order_id:
        params["origClientOrderId"] = client_order_id

    body = await signed_get("/fapi/v1/order", params, client=client)
    if not isinstance(body, dict):
        log.warning(
            "binance_order.get_order_status.no_body symbol=%s "
            "order_id=%s client_order_id=%s",
            symbol, order_id, client_order_id,
        )
        return OrderResult(
            submitted=False,
            dry_run_request=None,
            order_id=order_id,
            client_order_id=client_order_id,
            status=None,
            executed_qty=None,
            avg_price=None,
            cum_quote=None,
            error_code=None,
            error_msg="no_response_body_from_signed_get",
            gate_blocked=None,
            error_slug=None,
        )

    # The /fapi/v1/order GET response has the same shape as the POST
    # response in the happy path, so we reuse the parser.
    return _parse_binance_response(body, client_order_id=client_order_id)


async def cancel_order(
    symbol: str,
    *,
    order_id: int | None = None,
    client_order_id: str | None = None,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any] | None:
    """Cancel an open order via `DELETE /fapi/v1/order`.

    For MARKET orders this is rarely useful — they fill immediately. The
    helper is here for LIMIT iterations (G6.5+) and for cleanup paths in
    test scaffolding.

    Args:
        symbol: One of ALLOWED_SYMBOLS.
        order_id: OR client_order_id — at least one required.
        client_order_id: idempotency id from a prior submit.
        client: Optional shared httpx.AsyncClient.

    Returns:
        Binance's response body dict on success (includes the canceled
        order's final state), None on whitelist / id-missing failure or
        any transport / parse error.
    """
    if symbol not in ALLOWED_SYMBOLS:
        log.warning("binance_order.cancel_order.bad_symbol symbol=%s", symbol)
        return None
    if order_id is None and not client_order_id:
        log.warning(
            "binance_order.cancel_order.no_id symbol=%s — "
            "must supply order_id or client_order_id", symbol,
        )
        return None

    params: dict[str, str | int | float] = {"symbol": symbol}
    if order_id is not None:
        params["orderId"] = order_id
    elif client_order_id:
        params["origClientOrderId"] = client_order_id

    body = await signed_delete("/fapi/v1/order", params, client=client)
    if not isinstance(body, dict):
        log.warning(
            "binance_order.cancel_order.no_body symbol=%s "
            "order_id=%s client_order_id=%s",
            symbol, order_id, client_order_id,
        )
        return None
    return body


__all__ = [
    "ALLOWED_SIDES",
    "ALLOWED_SYMBOLS",
    "ALLOWED_TYPES",
    "OrderRequest",
    "OrderResult",
    "cancel_order",
    "get_order_status",
    "place_market_order",
]
